source 'https://rubygems.org'
ruby '1.9.3'

gem 'rails', '4.0.4'

group :development do
  gem 'sqlite3', '1.3.9'
end

gem 'sass-rails', '4.0.3'
gem 'uglifier', '2.5.0'
gem 'coffee-rails', '4.0.1'
gem 'jquery-rails', '3.1.0'
gem 'turbolinks', '2.2.2'
gem 'jbuilder', '1.0.2'

group :doc do
  gem 'sdoc', '0.4.0', require:false
end